### ISSUE TITLE
error	host.piheizung instance system.adapter.viessmann.0 terminated with code 1 ()

### ISSUE THREAD

**Issue by Sineos** [misanorot/iobroker.viessmann#10]
iobroker and the Viessmann adapter (0.2.4) are running on a RPi3 together with vcontrold (r107).

vcontrold works and is responding to "telnet 127.0.0.1 3002" just fine.
In iobroker I can't get the Viessmann adapter running, it immediately quits with:
```
piheizung	2017-01-23 19:57:35.871	error	host.piheizung instance system.adapter.viessmann.0 terminated with code 1 ()
piheizung	2017-01-23 19:57:35.506	info	host.piheizung instance system.adapter.viessmann.0 started with pid 23376
piheizung	2017-01-23 19:57:27.486	info	host.piheizung Restart adapter system.adapter.viessmann.0 because enabled
```

I tried to run with my full blown vito.xml as well as a reduced json version:

```
{
  "vito": {
    "devices": {
      "device": {
        "-ID": "20CB",
        "-name": "VScotHO1",
        "-protocol": "KW2"
      }
    },
    "commands": {
      "command": [
        {
          "-name": "getTempA",
          "-protocmd": "getaddr",
          "addr": "0800",
          "len": "2",
          "unit": "UT",
          "description": "Außentemperatur in °C"
        },
        {
          "-name": "getTempATp",
          "-protocmd": "getaddr",
          "addr": "5525",
          "len": "2",
          "unit": "UT",
          "description": "Außentemperatur in °C (Tiefpass)"
        }
      ]
    }
  }
}
```
It always ends with this error. As the error message is rather unspecific, I do not know what else to check. Any hint would be appreciated.

**Comment by Sineos** [comment]
Ok, this one was easy:

```
/opt/iobroker/node_modules/iobroker.viessmann/main.js:304
                adapter.setState('info.connection", false, true);
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

Mix between " and '. Works now. Many thanks for this adapter.

**Comment by misanorot** [comment]
Thanks!
