### ISSUE TITLE
Abfrageprobleme nach einem erfolgreichen Intervall

### ISSUE THREAD

**Issue by ingel81** [misanorot/ioBroker.viessmann#103]
Hi, 

kein richtiger Issue mit dem Adapter, eher eine Frage: 

Du lässt vermutlich den Socket des Adapters auf den vcocntrold offen zwischen den Polling Versuchen oder?

Habe aktuell dieses Problem mit vcontrold was mich davon abhält den Adapter zu verwenden:
https://github.com/openv/vcontrold/issues/127

Zusammengefasst: Der erste Connect auf den vcontrold (nach einem Adapterneustart) funktioniert und ich bekomme auch alle Werte geliefert. Jeder weitere Versuch geht schief. Telnet verhält sich allerdings identisch - Daher natürlich kein primäres Problem des Adapters sondern eher mit meinem vcontrold.

Allerdings bringt auch die Option "Neustart bei zu vielen Fehlern" im Adapter hier leider nichts. ioBroker identifiziert trotzdem eine ungefange Exception und damit einen Restart Loop des Adapters und schaltet ihn komplett ab. 

Lustigerweiße klappt mit dem vclient von openv alles hervorragend und auch hintereinandern. Einfach weil dieser immer den Socket zumacht nach einem erfolgreichen Abruf. Das wäre auch meine Notlösung mit vclient da selbst etwas zu basteln und die Daten an den mqtt broker vom ioBroker zu senden.

Ich hänge hier trotzdem mal ein Adapter Log an, evtl. fällt dir ja etwas auf. Ansonsten bitte einfach zu machen.

Grüße

```
2023-03-01 16:09:18.954 - info: host.c5769124e47d "system.adapter.viessmann.0" disabled
2023-03-01 16:09:18.955 - info: host.c5769124e47d stopInstance system.adapter.viessmann.0 (force=false, process=true)
2023-03-01 16:09:18.993 - info: viessmann.0 (7843) Got terminate signal TERMINATE_YOURSELF
2023-03-01 16:09:18.993 - info: viessmann.0 (7843) cleaned everything up...
2023-03-01 16:09:18.993 - info: viessmann.0 (7843) terminating
2023-03-01 16:09:18.994 - info: viessmann.0 (7843) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2023-03-01 16:09:18.997 - info: host.c5769124e47d stopInstance system.adapter.viessmann.0 send kill signal
2023-03-01 16:09:19.573 - info: host.c5769124e47d instance system.adapter.viessmann.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2023-03-01 16:10:10.626 - info: host.c5769124e47d "system.adapter.viessmann.0" enabled
2023-03-01 16:10:10.702 - info: host.c5769124e47d instance system.adapter.viessmann.0 started with pid 7872
2023-03-01 16:10:12.131 - info: viessmann.0 (7872) starting. Version 1.4.2 in /opt/iobroker/node_modules/iobroker.viessmann, node: v16.19.0, js-controller: 4.0.24
2023-03-01 16:10:12.147 - info: viessmann.0 (7872) Connect with Viessmann sytem!
2023-03-01 16:10:47.470 - warn: viessmann.0 (7872) Vctrld send ERROR: ERR: FRAMER: enable read failure for ack
Error opening /dev/ttyUSB0
2023-03-01 16:11:00.004 - info: javascript.0 (187) script.js.panels.fix_states.wallpanel-eg-ensure-wallpanel-started: 28.319
2023-03-01 16:11:23.874 - warn: viessmann.0 (7872) Vctrld send ERROR: ERR: FRAMER: read failure 1
Error in send, terminating
Error executing getCurrentPower
2023-03-01 16:11:28.885 - warn: viessmann.0 (7872) Vctrld send ERROR: ERR: FRAMER: read failure 1
Error in send, terminating
Error executing getBufferTemp1
2023-03-01 16:11:33.976 - warn: viessmann.0 (7872) Vctrld send ERROR: ERR: FRAMER: read failure 1
Error in send, terminating
Error executing getBufferTemp3
2023-03-01 16:11:39.096 - warn: viessmann.0 (7872) Vctrld send ERROR: ERR: FRAMER: read failure 1
Error in send, terminating
Error executing getHC2InletTemp
2023-03-01 16:11:54.485 - warn: viessmann.0 (7872) Vctrld send ERROR: ERR: FRAMER: read failure 1
Error in send, terminating
Error executing getCurrentPower
2023-03-01 16:11:59.500 - warn: viessmann.0 (7872) Vctrld send ERROR: ERR: FRAMER: read failure 1
Error in send, terminating
Error executing getBufferTemp1
2023-03-01 16:11:59.502 - warn: viessmann.0 (7872) Vctrld send too many errors, restart connection!
2023-03-01 16:11:59.505 - info: viessmann.0 (7872) Connection with Viessmann system disconnected!
2023-03-01 16:12:01.691 - info: host.c5769124e47d "system.adapter.viessmann.0" disabled
2023-03-01 16:12:01.693 - info: host.c5769124e47d stopInstance system.adapter.viessmann.0 (force=false, process=true)
2023-03-01 16:12:01.765 - info: host.c5769124e47d stopInstance system.adapter.viessmann.0 send kill signal
2023-03-01 16:12:01.765 - info: viessmann.0 (7872) Got terminate signal TERMINATE_YOURSELF
2023-03-01 16:12:01.766 - info: viessmann.0 (7872) cleaned everything up...
2023-03-01 16:12:01.766 - info: viessmann.0 (7872) terminating
2023-03-01 16:12:01.766 - info: viessmann.0 (7872) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2023-03-01 16:12:02.319 - info: host.c5769124e47d instance system.adapter.viessmann.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2023-03-01 16:12:04.872 - info: host.c5769124e47d "system.adapter.viessmann.0" enabled
2023-03-01 16:12:04.928 - info: host.c5769124e47d instance system.adapter.viessmann.0 started with pid 7903
2023-03-01 16:12:06.454 - info: viessmann.0 (7903) starting. Version 1.4.2 in /opt/iobroker/node_modules/iobroker.viessmann, node: v16.19.0, js-controller: 4.0.24
2023-03-01 16:12:06.470 - info: viessmann.0 (7903) Connect with Viessmann sytem!
2023-03-01 16:13:12.870 - warn: viessmann.0 (7903) Vctrld send ERROR: ERR: FRAMER: read failure 1
Error in send, terminating
Error executing getBurnerStarts
2023-03-01 16:13:17.970 - warn: viessmann.0 (7903) Vctrld send ERROR: ERR: FRAMER: read failure 1
Error in send, terminating
Error executing getCurrentPower
2023-03-01 16:13:23.085 - warn: viessmann.0 (7903) Vctrld send ERROR: ERR: FRAMER: read failure 1
Error in send, terminating
Error executing getBufferTemp2
2023-03-01 16:13:28.097 - warn: viessmann.0 (7903) Vctrld send ERROR: ERR: FRAMER: read failure 1
Error in send, terminating
Error executing getBufferTemp3
2023-03-01 16:13:33.182 - warn: viessmann.0 (7903) Vctrld send ERROR: ERR: FRAMER: read failure 1
Error in send, terminating
Error executing getHC2InletTemp
2023-03-01 16:13:43.375 - warn: viessmann.0 (7903) Vctrld send ERROR: ERR: FRAMER: read failure 1
Error in send, terminating
Error executing getBurnerStarts
2023-03-01 16:13:43.376 - warn: viessmann.0 (7903) Vctrld send too many errors, restart connection!
2023-03-01 16:13:43.380 - info: viessmann.0 (7903) Connection with Viessmann system disconnected!
2023-03-01 16:13:53.380 - error: viessmann.0 (7903) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-03-01 16:13:53.381 - error: viessmann.0 (7903) unhandled promise rejection: this.setStateAsync is not a function
2023-03-01 16:13:53.383 - error: viessmann.0 (7903) TypeError: this.setStateAsync is not a function
at Timeout.main [as _onTimeout] (/opt/iobroker/node_modules/iobroker.viessmann/main.js:584:8)
at listOnTimeout (node:internal/timers:559:17)
at processTimers (node:internal/timers:502:7)
2023-03-01 16:13:53.383 - error: viessmann.0 (7903) this.setStateAsync is not a function
2023-03-01 16:13:53.388 - info: viessmann.0 (7903) cleaned everything up...
2023-03-01 16:13:53.389 - info: viessmann.0 (7903) terminating
2023-03-01 16:13:53.390 - warn: viessmann.0 (7903) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-03-01 16:13:53.950 - error: host.c5769124e47d instance system.adapter.viessmann.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-03-01 16:13:53.950 - info: host.c5769124e47d Restart adapter system.adapter.viessmann.0 because enabled
2023-03-01 16:14:00.006 - info: javascript.0 (187) script.js.panels.fix_states.wallpanel-eg-ensure-wallpanel-started: 21.589
2023-03-01 16:14:24.018 - info: host.c5769124e47d instance system.adapter.viessmann.0 started with pid 7934
2023-03-01 16:14:25.514 - info: viessmann.0 (7934) starting. Version 1.4.2 in /opt/iobroker/node_modules/iobroker.viessmann, node: v16.19.0, js-controller: 4.0.24
2023-03-01 16:14:25.529 - info: viessmann.0 (7934) Connect with Viessmann sytem!
2023-03-01 16:15:00.004 - info: javascript.0 (187) script.js.panels.fix_states.wallpanel-eg-ensure-wallpanel-started: 20.113
2023-03-01 16:15:31.962 - warn: viessmann.0 (7934) Vctrld send ERROR: ERR: FRAMER: read failure 1
Error in send, terminating
Error executing getBurnerStarts
2023-03-01 16:15:42.108 - warn: viessmann.0 (7934) Vctrld send ERROR: ERR: FRAMER: read failure 1
Error in send, terminating
Error executing getBufferTemp1
2023-03-01 16:15:47.211 - warn: viessmann.0 (7934) Vctrld send ERROR: ERR: FRAMER: read failure 1
Error in send, terminating
Error executing getBufferTemp3
2023-03-01 16:15:52.275 - warn: viessmann.0 (7934) Vctrld send ERROR: ERR: FRAMER: read failure 1
Error in send, terminating
Error executing getHC2InletTemp
2023-03-01 16:16:07.661 - warn: viessmann.0 (7934) Vctrld send ERROR: ERR: FRAMER: read failure 1
Error in send, terminating
Error executing getCurrentPower
2023-03-01 16:16:17.767 - warn: viessmann.0 (7934) Vctrld send ERROR: ERR: FRAMER: read failure 1
Error in send, terminating
Error executing getBufferTemp3
2023-03-01 16:16:17.768 - warn: viessmann.0 (7934) Vctrld send too many errors, restart connection!
2023-03-01 16:16:17.772 - info: viessmann.0 (7934) Connection with Viessmann system disconnected!
2023-03-01 16:16:27.771 - error: viessmann.0 (7934) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-03-01 16:16:27.771 - error: viessmann.0 (7934) unhandled promise rejection: this.setStateAsync is not a function
2023-03-01 16:16:27.771 - error: viessmann.0 (7934) TypeError: this.setStateAsync is not a function
at Timeout.main [as _onTimeout] (/opt/iobroker/node_modules/iobroker.viessmann/main.js:584:8)
at listOnTimeout (node:internal/timers:559:17)
at processTimers (node:internal/timers:502:7)
2023-03-01 16:16:27.771 - error: viessmann.0 (7934) this.setStateAsync is not a function
2023-03-01 16:16:27.772 - info: viessmann.0 (7934) cleaned everything up...
2023-03-01 16:16:27.772 - info: viessmann.0 (7934) terminating
2023-03-01 16:16:27.773 - warn: viessmann.0 (7934) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-03-01 16:16:28.349 - error: host.c5769124e47d instance system.adapter.viessmann.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-03-01 16:16:28.349 - info: host.c5769124e47d Restart adapter system.adapter.viessmann.0 because enabled
2023-03-01 16:16:58.406 - info: host.c5769124e47d instance system.adapter.viessmann.0 started with pid 7963
2023-03-01 16:16:59.955 - info: viessmann.0 (7963) starting. Version 1.4.2 in /opt/iobroker/node_modules/iobroker.viessmann, node: v16.19.0, js-controller: 4.0.24
2023-03-01 16:17:00.022 - info: viessmann.0 (7963) Connect with Viessmann sytem!
```

**Comment by misanorot** [comment]
Hi,

bin definitiv nicht der vcontrold Experte, aber das:

Vctrld send ERROR: ERR: FRAMER: enable read failure for ack
Error opening /dev/ttyUSB0

ist vermutlich ursächlich.

**Comment by ingel81** [comment]
> Und ja, die Verbindung lasse ich offen.

Danke dir für die schnelle Rückmeldung. Bestätigt meine Theorie. Dann hoffe ich mal auf eine Rückmeldung beim vcontrold Projekt. 

Eventuell muss ich auch einmal eine andere vcontrold Version testen. Kommunikationsprobleme optischer Art würde ich fast ausschließen da mit vclient ja alles problemlos und reproduzierbar klappt. Sogar viele Commands in einem Rutsch.
