### ISSUE TITLE
update to iobroker 5.0.3 breaks Viessmann adapter

### ISSUE THREAD

**Issue by olli-70** [misanorot/ioBroker.viessmann#121]
after update to js-controller (with upgrade self) Viessmann adapter does not work anymore.

js-controller v5.0.3 (docker based)
viessmann  v1.4.3
npm: 18.16.09.5.1

node 
`2023-06-15 07:59:28.168  - error: viessmann.0 (2609) Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-15 07:59:28.185  - warn: viessmann.0 (2609) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-06-15 07:59:28.771  - error: host.iobroker instance system.adapter.viessmann.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-06-15 07:59:28.772  - info: host.iobroker Restart adapter system.adapter.viessmann.0 because enabled
2023-06-15 07:59:59.114  - info: host.iobroker instance system.adapter.viessmann.0 started with pid 2656
2023-06-15 08:00:02.139  - error: viessmann.0 (2656) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-06-15 08:00:02.140  - error: viessmann.0 (2656) unhandled promise rejection: Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-15 08:00:02.142  - error: viessmann.0 (2656) Error: Parameter "options" needs to be a real object but type "boolean" has been passed
    at Viessmann.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5331:35)
    at Viessmann.setStateAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2006:16)
    at Viessmann.main (/opt/iobroker/node_modules/iobroker.viessmann/main.js:588:8)
    at Viessmann.startAdapter (/opt/iobroker/node_modules/iobroker.viessmann/main.js:116:15)
    at Viessmann.onReady (/opt/iobroker/node_modules/iobroker.viessmann/main.js:55:9)
    at Viessmann.emit (node:events:513:28)
    at Viessmann._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9017:18)
2023-06-15 08:00:02.142  - error: viessmann.0 (2656) Parameter "options" needs to be a real object but type "boolean" has been passed
2023-06-15 08:00:02.162  - warn: viessmann.0 (2656) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-06-15 08:00:02.761  - error: host.iobroker instance system.adapter.viessmann.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-06-15 08:00:02.762  - info: host.iobroker Restart adapter system.adapter.viessmann.0 because enabled
2023-06-15 08:00:02.762  - warn: host.iobroker Do not restart adapter system.adapter.viessmann.0 because restart loop detected`

**Comment by Huskerdu24** [comment]
The same here. See my topic in [https://github.com/misanorot/ioBroker.viessmann/issues/110#issuecomment-1591879555](url)

**Comment by misanorot** [comment]
Fixed 1.4.4
