### ISSUE TITLE
Unhandled Promise während Neustart

### ISSUE THREAD

**Issue by Boronsbruder** [misanorot/ioBroker.viessmann#135]
Als der vcontrold vermehrt Fehler sendete, startete die Instanz wie gewollt neu. Produzierte dabei aber ein 'unhandled Promise'

```
2023-08-13 09:02:21.414  - warn: viessmann.0 (4165756) Vctrld send too many errors, restart connection!
2023-08-13 09:02:21.415  - info: viessmann.0 (4165756) Connection with Viessmann system disconnected!
2023-08-13 09:02:31.416  - error:  viessmann.0 (4165756) Unhandled promise rejection. This error  originated either by throwing inside of an async function without a  catch block, or by rejecting a promise which was not handled with  .catch().
2023-08-13 09:02:31.417  - error: viessmann.0 (4165756) unhandled promise rejection: this.setStateAsync is not a function
2023-08-13 09:02:31.417  - error: viessmann.0 (4165756) TypeError: this.setStateAsync is not a function
at Timeout.main [as _onTimeout] (/opt/iobroker/node_modules/iobroker.viessmann/main.js:582:8)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
2023-08-13 09:02:31.417  - error: viessmann.0 (4165756) this.setStateAsync is not a function
2023-08-13 09:02:31.419  - info: viessmann.0 (4165756) cleaned everything up...
2023-08-13 09:02:31.419  - info: viessmann.0 (4165756) terminating
2023-08-13 09:02:31.420  - warn: viessmann.0 (4165756) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-08-13 09:02:32.063  - error: host.zerobroker instance system.adapter.viessmann.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-08-13 09:02:32.064  - info: host.zerobroker Restart adapter system.adapter.viessmann.0 because enabled
2023-08-13 09:03:02.192  - info: host.zerobroker instance system.adapter.viessmann.0 started with pid 3007288
```
**Versions:**  
 - Adapter version: 1.4.4
 - JS-Controller version: 4.0.24
 - Node version: v18.17.0
 - Operating system: Debian bullseye - 5.10.0-23-amd64

**Comment by misanorot** [comment]
Hallo, danach ist die Instanz normal gestartet???

**Comment by Boronsbruder** [comment]
Ja, hat nur während des Stoppens den Fehler raus gehaun. Dananch lief die Instanz wieder.

**Comment by misanorot** [comment]
sollte mit 1.4.5 weg sein, ggf. nochmal melden, da ich es nicht testen konnte.

**Comment by Boronsbruder** [comment]
Fast...
Ich hab vorhin meinen Kessel abgeschalten, weil ich den Aussenfühler ausgetauscht habe.
Resultat:
```
2023-08-22 11:17:37.550  - warn: viessmann.0 (2523887) Vctrld send ERROR: ERR: read timeout
--
Error in wait, terminating
Error executing getError1
2023-08-22 11:17:42.551  - warn: viessmann.0 (2523887) Vctrld send ERROR: ERR: read timeout
Error in wait, terminating
Error executing getError2
vctrld>
2023-08-22 11:17:47.553  - warn: viessmann.0 (2523887) Vctrld send ERROR: ERR: read timeout
Error in wait, terminating
Error executing getError3
2023-08-22 11:17:52.554  - warn: viessmann.0 (2523887) Vctrld send ERROR: ERR: read timeout
Error in wait, terminating
Error executing getError4
vctrld>
2023-08-22 11:17:57.555  - warn: viessmann.0 (2523887) Vctrld send ERROR: ERR: read timeout
Error in wait, terminating
Error executing getError5
2023-08-22 11:18:02.557  - warn: viessmann.0 (2523887) Vctrld send ERROR: ERR: read timeout
Error in wait, terminating
Error executing getError6
vctrld>
2023-08-22 11:18:02.558  - warn: viessmann.0 (2523887) Vctrld send too many errors, restart connection!
2023-08-22 11:18:02.559  - info: viessmann.0 (2523887) Connection with Viessmann system disconnected!
2023-08-22 11:18:12.560  - error:  viessmann.0 (2523887) Unhandled promise rejection. This error  originated either by throwing inside of an async function without a  catch block, or by rejecting a promise which was not handled with  .catch().
2023-08-22 11:18:12.561  - error: viessmann.0 (2523887) unhandled promise rejection: this.setState is not a function
2023-08-22 11:18:12.562  - error: viessmann.0 (2523887) TypeError: this.setState is not a function
at Timeout.main [as _onTimeout] (/opt/iobroker/node_modules/iobroker.viessmann/main.js:582:8)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
2023-08-22 11:18:12.562  - error: viessmann.0 (2523887) this.setState is not a function
2023-08-22 11:18:12.565  - info: viessmann.0 (2523887) cleaned everything up...
2023-08-22 11:18:12.566  - info: viessmann.0 (2523887) terminating
2023-08-22 11:18:12.566  - warn: viessmann.0 (2523887) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-08-22 11:18:13.217  - error: host.zerobroker instance system.adapter.viessmann.0 terminated with code 6 
```
