### ISSUE TITLE
Crash caused by ssh (1.3.5)

### ISSUE THREAD

**Issue by Scrounger** [misanorot/ioBroker.viessmann#80]
**Describe the bug**  
Adapter crash after updating. Seems that ssh lib update caused this:
https://github.com/misanorot/ioBroker.viessmann/commit/12d6ac711031451dba4b6c0b2589860b3c8f4448

**Screenshots & Logfiles**  
```
2022-04-04 15:10:42.644  - info: viessmann.0 (12226) starting. Version 1.3.5 in /opt/iobroker/node_modules/iobroker.viessmann, node: v14.19.0, js-controller: 4.0.21
2022-04-04 15:10:42.655  - error: viessmann.0 (12226) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-04-04 15:10:42.655  - error: viessmann.0 (12226) unhandled promise rejection: ssh is not a constructor
2022-04-04 15:10:42.656  - error: viessmann.0 (12226) TypeError: ssh is not a constructor
    at readxml (/opt/iobroker/node_modules/iobroker.viessmann/main.js:151:24)
    at Object.start [as ready] (/opt/iobroker/node_modules/iobroker.viessmann/main.js:121:40)
2022-04-04 15:10:42.656  - error: viessmann.0 (12226) ssh is not a constructor
2022-04-04 15:10:43.160  - info: viessmann.0 (12226) terminating
2022-04-04 15:10:43.161  - warn: viessmann.0 (12226) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-04-04 15:10:43.694  - error: host.ioBroker instance system.adapter.viessmann.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
```

**Versions:**  
 - Adapter version: 1.3.5
 - JS-Controller version:  4.0.21
 - Operating system: ubuntu

**Comment by misanorot** [comment]
please try 1.3.6

**Comment by Scrounger** [comment]
works now, great thank you.
